import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
  atom,
  useQuery,
  useMutation,
  Connect
} from '../libs/atomic-state'

interface State {
  text: string
}

type CountRef = number

const helloRef = atom({
  defaultState: { text: 'Hello world' }
})

const countRef = atom({
  defaultState: 0
})

const setCount = (_: CountRef, newCount: number) => newCount

const SubComponent = () => {
  const count = useQuery(countRef, (s) => s)
  const mutate = useMutation(countRef)

  return (
    <div>
      <input
        type="number"
        value={count}
        onChange={(ev) => {
          mutate(setCount, Number(ev.target.value))
        }}
      />
    </div>
  )
}

const setText = (_: State, text: string) => ({ text })

const AtomicStateDemo = () => {
  const state = useQuery(helloRef, (s) => s)
  const mutate = useMutation(helloRef)

  return (
    <div>
      <input
        type="text"
        value={state.text}
        onChange={(ev) => {
          mutate(setText, ev.target.value)
        }}
      />
      {state.text.length > 0 && (
        <Connect atoms={[countRef]}>
          <SubComponent />
        </Connect>
      )}
    </div>
  )
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Atomic State</h1>

        <Connect atoms={[helloRef]}>
          <AtomicStateDemo />
        </Connect>
      </main>
    </div>
  )
}

export default Home
